"""Initial migration for PostgreSQL

Revision ID: 0cfdfa10d986
Revises: 
Create Date: 2025-06-30 11:14:30.237733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfdfa10d986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_column('deep_scan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deep_scan', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
