"""Reset migration

Revision ID: 1ba40399b4d0
Revises: e18768969344
Create Date: 2025-02-13 16:27:27.147443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba40399b4d0'
down_revision = 'e18768969344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_urls_into_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_key')

    op.drop_table('change_urls_into_payloads')
    # ### end Alembic commands ###
