"""Auto migration

Revision ID: 24da4e3917b5
Revises: f5e6cc6a567e
Create Date: 2025-02-27 23:31:33.356797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '24da4e3917b5'
down_revision = 'f5e6cc6a567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paramspider_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paramspider_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id')
    )
    op.drop_table('harvester_results')
    with op.batch_alter_table('xss_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_xss', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xss_result', schema=None) as batch_op:
        batch_op.drop_column('if_xss')

    op.create_table('harvester_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('scan_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('urls', sqlite.JSON(), nullable=True),
    sa.Column('emails', sqlite.JSON(), nullable=True),
    sa.Column('subdomains', sqlite.JSON(), nullable=True),
    sa.Column('hosts', sqlite.JSON(), nullable=True),
    sa.Column('social_media', sqlite.JSON(), nullable=True),
    sa.Column('dns_records', sqlite.JSON(), nullable=True),
    sa.Column('scan_sources', sa.VARCHAR(length=255), nullable=True),
    sa.Column('limit', sa.INTEGER(), nullable=True),
    sa.Column('direct_ips', sqlite.JSON(), nullable=True),
    sa.Column('ip_ranges', sqlite.JSON(), nullable=True),
    sa.Column('cdn_ips', sqlite.JSON(), nullable=True),
    sa.Column('reverse_dns', sqlite.JSON(), nullable=True),
    sa.Column('asn_info', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paramspider_result')
    # ### end Alembic commands ###
