"""Reset migration

Revision ID: 51df9f3f0c46
Revises: d12f69efe7c6
Create Date: 2025-02-16 19:06:59.316889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51df9f3f0c46'
down_revision = 'd12f69efe7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paramspider_results')
    op.drop_table('change_urls_into_payloads')
    with op.batch_alter_table('harvester_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('file_urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('api_endpoints', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('emails', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('subdomains', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('hosts', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ports', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('people', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dns_records', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('search_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scan_sources', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('limit', sa.Integer(), nullable=True))
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvester_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.TEXT(), nullable=True))
        batch_op.drop_column('limit')
        batch_op.drop_column('scan_sources')
        batch_op.drop_column('search_results')
        batch_op.drop_column('dns_records')
        batch_op.drop_column('social_media')
        batch_op.drop_column('people')
        batch_op.drop_column('ports')
        batch_op.drop_column('hosts')
        batch_op.drop_column('subdomains')
        batch_op.drop_column('emails')
        batch_op.drop_column('api_endpoints')
        batch_op.drop_column('file_urls')
        batch_op.drop_column('urls')
        batch_op.drop_column('status')

    op.create_table('change_urls_into_payloads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payload', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paramspider_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('exclude', sa.VARCHAR(length=255), nullable=True),
    sa.Column('threads', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('result_text', sa.TEXT(), nullable=True),
    sa.Column('total_urls', sa.INTEGER(), nullable=True),
    sa.Column('unique_parameters', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id')
    )
    # ### end Alembic commands ###
