"""Initial migration

Revision ID: 662af39ccb14
Revises: 
Create Date: 2025-02-09 11:49:06.298769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662af39ccb14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('client_ip', sa.String(length=39), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('zombie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=39), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zombie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zombie_username'), ['username'], unique=True)

    op.create_table('command__user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_run', sa.Boolean(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_zombie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_run', sa.Boolean(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zombie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_ip', sa.String(length=255), nullable=False),
    sa.Column('target_ip_no_https', sa.String(length=255), nullable=False),
    sa.Column('target_port', sa.Integer(), nullable=True),
    sa.Column('target_username', sa.String(length=50), nullable=True),
    sa.Column('target_password', sa.String(length=50), nullable=True),
    sa.Column('target_status', sa.String(length=50), nullable=True),
    sa.Column('deep_scan', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_each_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crtsh__result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('total_domains', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], name='fk_crtsh_target'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_crtsh_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nmap_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_result', sa.Text(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paramspider_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('exclude', sa.String(length=255), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=True),
    sa.Column('unique_parameters', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id')
    )
    op.create_table('webtech__result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('webtech_result', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('web_tech', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_each_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form', sa.Text(), nullable=False),
    sa.Column('form_method', sa.String(length=10), nullable=True),
    sa.Column('form_action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('crawler_each_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_each_url_id'], ['crawler_each_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_each_html',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('crawler_each_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_each_url_id'], ['crawler_each_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_each_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('crawler_each_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_each_url_id'], ['crawler_each_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_each_js',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('js', sa.Text(), nullable=False),
    sa.Column('js_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('crawler_each_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_each_url_id'], ['crawler_each_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawler_each_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('crawler_each_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_each_url_id'], ['crawler_each_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('if_sql_injection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('sql_injection', sa.Text(), nullable=False),
    sa.Column('crawler_each_url_id', sa.Integer(), nullable=False),
    sa.Column('if_sql_injection', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_each_url_id'], ['crawler_each_url.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('param_type', sa.String(length=50), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['crawler_each_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_parameter')
    op.drop_table('if_sql_injection')
    op.drop_table('crawler_each_security')
    op.drop_table('crawler_each_js')
    op.drop_table('crawler_each_image')
    op.drop_table('crawler_each_html')
    op.drop_table('crawler_each_form')
    op.drop_table('webtech__result')
    op.drop_table('paramspider_results')
    op.drop_table('nmap_result')
    op.drop_table('crtsh__result')
    op.drop_table('crawler_each_url')
    op.drop_table('target')
    op.drop_table('command_zombie')
    op.drop_table('command__user')
    with op.batch_alter_table('zombie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zombie_username'))

    op.drop_table('zombie')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('payload')
    # ### end Alembic commands ###
