"""Auto migration

Revision ID: 89cd84cb4750
Revises: 24da4e3917b5
Create Date: 2025-02-27 23:49:32.291927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cd84cb4750'
down_revision = '24da4e3917b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paramspider_result', schema=None) as batch_op:
        batch_op.alter_column('paramspider_result',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paramspider_result', schema=None) as batch_op:
        batch_op.alter_column('paramspider_result',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
