"""Auto migration

Revision ID: f5e6cc6a567e
Revises: 51df9f3f0c46
Create Date: 2025-02-16 20:17:13.480458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f5e6cc6a567e'
down_revision = '51df9f3f0c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvester_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direct_ips', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip_ranges', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cdn_ips', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reverse_dns', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('asn_info', sa.JSON(), nullable=True))
        batch_op.drop_column('people')
        batch_op.drop_column('search_results')
        batch_op.drop_column('file_urls')
        batch_op.drop_column('ports')
        batch_op.drop_column('api_endpoints')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvester_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_endpoints', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ports', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('file_urls', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('search_results', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('people', sqlite.JSON(), nullable=True))
        batch_op.drop_column('asn_info')
        batch_op.drop_column('reverse_dns')
        batch_op.drop_column('cdn_ips')
        batch_op.drop_column('ip_ranges')
        batch_op.drop_column('direct_ips')

    # ### end Alembic commands ###
