version: '3.8'

services:
  postgres:
    image: postgres:13-bullseye
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup_user_db.sh:/docker-entrypoint-initdb.d/setup_user_db.sh
      - ./sql_scripts:/docker-entrypoint-initdb.d/sql_scripts
    restart: unless-stopped
volumes:
  postgres_data: